import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import Wallets from '@/components/Wallets/Wallets'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <a href="https://eips.ethereum.org/EIPS/eip-5749" rel='no-referrer' target="_blank"><h1>EIP-5749</h1></a>
        <Wallets/>
      </main>
    </>
  )
}
